version: '3.9'

services:
  mysql-db:
    image: mysql:8.0
    container_name: Software_Development_V
    environment:
      MYSQL_ROOT_PASSWORD: mySecretPassword
      MYSQL_DATABASE: RestaurantDB
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
